package no.nav.k9.los.nyoppgavestyring.domeneadaptere.k9

import no.nav.k9.los.nyoppgavestyring.mottak.feltdefinisjon.Feltdefinisjon
import no.nav.k9.los.nyoppgavestyring.mottak.feltdefinisjon.Feltdefinisjoner
import no.nav.k9.los.nyoppgavestyring.mottak.feltdefinisjon.Kodeverkreferanse
import no.nav.k9.los.nyoppgavestyring.mottak.feltdefinisjon.Synlighet
import no.nav.k9.los.nyoppgavestyring.mottak.omraade.Område
import no.nav.k9.los.nyoppgavestyring.query.mapping.transientfeltutleder.*

object K9Feltdefinisjoner {

    fun lagFeltdefinisjoner(område: Område): Feltdefinisjoner {
        return Feltdefinisjoner(
            område = område,
            feltdefinisjoner = setOf(
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.BEHANDLING_UUID,
                    område = område,
                    visningsnavn = "Behandling",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.INTERNT,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.PAKLAGET_BEHANDLING_UUID,
                    område = område,
                    visningsnavn = "Påklaget behandling",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.INTERNT,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.PAKLAGET_BEHANDLINGTYPE,
                    område = område,
                    visningsnavn = "Påklaget behandlingtype",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKTOR_ID,
                    område = område,
                    visningsnavn = "Søkers aktør-ID",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.INTERNT,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.FAGSYSTEM,
                    område = område,
                    visningsnavn = "Fagsystem",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "Fagsystem"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.SAKSNUMMER,
                    område = område,
                    visningsnavn = "Saksnummer",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.RESULTATTYPE,
                    område = område,
                    visningsnavn = "Resultattype",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "Resultattype"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.BEHANDLINGSSTEG,
                    område = område,
                    visningsnavn = "Behandlingssteg",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "Behandlingssteg"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.YTELSESTYPE,
                    område = område,
                    visningsnavn = "Ytelsestype",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "Ytelsetype"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.BEHANDLINGSSTATUS,
                    område = område,
                    visningsnavn = "Behandlingsstatus",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "Behandlingsstatus"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.MOTTATT_DATO,
                    område = område,
                    visningsnavn = "Mottatt dato",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Timestamp",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.TID_SIDEN_MOTTATT_DATO,
                    område = område,
                    visningsnavn = "Dager siden mottatt dato",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Duration",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = GyldigeTransientFeltutleder.hentFeltutleder(K9SakTidSidenMottattDatoUtleder::class.java.canonicalName)
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.REGISTRERT_DATO,
                    område = område,
                    visningsnavn = "Registrert dato",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Timestamp",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.BEHANDLING_TYPEKODE,
                    område = område,
                    visningsnavn = "Behandlingstype",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "Behandlingtype"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.RELATERT_PART_AKTORID,
                    område = område,
                    visningsnavn = "Relatert part aktør-ID",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.INTERNT,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.PLEIETRENGENDE_AKTOR_ID,
                    område = område,
                    visningsnavn = "Pleietrengende aktør-ID",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.INTERNT,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.BEHANDLENDE_ENHET,
                    område = område,
                    visningsnavn = "Behandlende enhet",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "behandlendeEnhet"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.ANSVARLIG_SAKSBEHANDLER,
                    område = område,
                    visningsnavn = "Ansvarlig saksbehandler",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.ANSVARLIG_BESLUTTER,
                    område = område,
                    visningsnavn = "Ansvarlig beslutter",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.LIGGER_HOS_BESLUTTER,
                    område = område,
                    visningsnavn = "Til beslutter",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "boolean",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.TID_FORSTE_GANG_HOS_BESLUTTER,
                    område = område,
                    visningsnavn = "Tidspunkt oppgaven gikk til beslutter første gang",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Timestamp",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.TOTRINNSKONTROLL,
                    område = område,
                    visningsnavn = "Må gjennom totrinnskontroll",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "boolean",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKSJONSPUNKT,
                    område = område,
                    visningsnavn = "Løsbare, fremtidige og tidligere aksjonspunkt",
                    beskrivelse = "Løsbare- (se aksjonspunkt som kan løses), fremtidige- (se Løsbare og fremtidige aksjonspunkt) og løste aksjonspunkt",
                    listetype = true,
                    tolkesSom = "String",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "Aksjonspunkt"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKTIVT_AKSJONSPUNKT,
                    område = område,
                    visningsnavn = "Løsbare og fremtidige aksjonspunkt",
                    beskrivelse = "Løsbare aksjonspunkt (se aksjonspunkt som kan løses) og åpne aksjonspunkter som kan løses først når behandlingen når riktig steg",
                    listetype = true,
                    tolkesSom = "String",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "Aksjonspunkt"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.LOSBART_AKSJONSPUNKT,
                    område = område,
                    visningsnavn = "Aksjonspunkt: løsbart",
                    beskrivelse = "Åpne aksjonspunkt som er løsbart akkurat nå, fordi de hører til steget behandlingen står i",
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "Aksjonspunkt"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.UTFORT_AKSJONSPUNKT,
                    område = område,
                    visningsnavn = "Aksjonspunkt: utførte",
                    beskrivelse = "Aksjonspunkter som er utført",
                    listetype = true,
                    tolkesSom = "String",
                    synlighet = Synlighet.SKJULT,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "Aksjonspunkt"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AVBRUTT_AKSJONSPUNKT,
                    område = område,
                    visningsnavn = "Aksjonspunkt: avbrutte",
                    beskrivelse = "Aksjonspunkter som er avbrutt",
                    listetype = true,
                    tolkesSom = "String",
                    synlighet = Synlighet.SKJULT,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "Aksjonspunkt"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.FREMTIDIG_AKSJONSPUNKT,
                    område = område,
                    visningsnavn = "Aksjonspunkt: fremtidige",
                    beskrivelse = "Åpne aksjonspunkter som ikke kan løses i steget behandlingen står i nå",
                    listetype = true,
                    tolkesSom = "String",
                    synlighet = Synlighet.SKJULT,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "Aksjonspunkt"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AVVENTER_SAKSBEHANDLER,
                    område = område,
                    visningsnavn = "Avventer saksbehandler",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "boolean",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AVVENTER_SOKER,
                    område = område,
                    visningsnavn = "Avventer søker",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "boolean",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AVVENTER_ARBEIDSGIVER,
                    område = område,
                    visningsnavn = "Avventer arbeidsgiver",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "boolean",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AVVENTER_TEKNISK_FEIL,
                    område = område,
                    visningsnavn = "Avventer teknisk feil",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "boolean",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AVVENTER_ANNET,
                    område = område,
                    visningsnavn = "Avventer annet",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "boolean",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AVVENTER_ANNET_IKKE_SAKSBEHANDLINGSTID,
                    område = område,
                    visningsnavn = "Avventer annet (ikke saksbehandlingstid)",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "boolean",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKKUMULERT_VENTETID_SAKSBEHANDLER_FOR_TIDLIGERE_VERSJONER,
                    område = område,
                    visningsnavn = "Akkumulert ventetid saksbehandler for tidligere versjoner",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Duration",
                    synlighet = Synlighet.INTERNT,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKKUMULERT_VENTETID_SOKER_FOR_TIDLIGERE_VERSJONER,
                    område = område,
                    visningsnavn = "Akkumulert ventetid søker for tidligere versjoner",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Duration",
                    synlighet = Synlighet.INTERNT,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKKUMULERT_VENTETID_TEKNISK_FEIL_FOR_TIDLIGERE_VERSJONER,
                    område = område,
                    visningsnavn = "Akkumulert ventetid teknisk feil for tidligere versjoner",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Duration",
                    synlighet = Synlighet.INTERNT,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKKUMULERT_VENTETID_ARBEIDSGIVER_FOR_TIDLIGERE_VERSJONER,
                    område = område,
                    visningsnavn = "Akkumulert ventetid arbeidsgiver for tidligere versjoner",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Duration",
                    synlighet = Synlighet.INTERNT,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKKUMULERT_VENTETID_ANNET_FOR_TIDLIGERE_VERSJONER,
                    område = område,
                    visningsnavn = "Akkumulert ventetid annet for tidligere versjoner",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Duration",
                    synlighet = Synlighet.INTERNT,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKKUMULERT_VENTETID_ANNET_IKKE_SAKSBEHANDLINGSTID_FOR_TIDLIGERE_VERSJONER,
                    område = område,
                    visningsnavn = "Akkumulert ventetid annet (ikke saksbehandlingstid) for tidligere versjoner",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Duration",
                    synlighet = Synlighet.INTERNT,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKKUMULERT_VENTETID_ANNET_IKKE_SAKSBEHANDLINGSTID,
                    område = område,
                    visningsnavn = "Hittil akkumulert ventetid på annet som ikke skal telle som saksbehandlingstid for denne oppgaven",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Duration",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = GyldigeTransientFeltutleder.hentFeltutleder(K9SakVentetPåAnnetIkkeSaksbehandlingstidUtleder::class.java.canonicalName)
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKKUMULERT_VENTETID_ANNET,
                    område = område,
                    visningsnavn = "Hittil akkumulert ventetid på annet for denne oppgaven",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Duration",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = GyldigeTransientFeltutleder.hentFeltutleder(K9SakVentetPåAnnetUtleder::class.java.canonicalName)
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKKUMULERT_VENTETID_ARBEIDSGIVER,
                    område = område,
                    visningsnavn = "Hittil akkumulert ventetid på arbeidsgiver for denne oppgaven",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Duration",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = GyldigeTransientFeltutleder.hentFeltutleder(K9SakVentetPåArbeidsgiverUtleder::class.java.canonicalName)
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKKUMULERT_VENTETID_SAKSBEHANDLER,
                    område = område,
                    visningsnavn = "Hittil akkumulert ventetid på saksbehandler for denne oppgaven",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Duration",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = GyldigeTransientFeltutleder.hentFeltutleder(K9SakVentetPåSaksbehandlerUtleder::class.java.canonicalName)
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKKUMULERT_VENTETID_SOKER,
                    område = område,
                    visningsnavn = "Hittil akkumulert ventetid på søker for denne oppgaven",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Duration",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = GyldigeTransientFeltutleder.hentFeltutleder(K9SakVentetPåSøkerUtleder::class.java.canonicalName)
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKKUMULERT_VENTETID_TEKNISK_FEIL,
                    område = område,
                    visningsnavn = "Hittil akkumulert ventetid på tekniske feil for denne oppgaven",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Duration",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = GyldigeTransientFeltutleder.hentFeltutleder(K9SakVentetPåTekniskFeilUtleder::class.java.canonicalName)
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.OPPGAVESAKSBEHANDLINGSTID,
                    område = område,
                    visningsnavn = "Oppgavesaksbehandlingstid",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Duration",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = GyldigeTransientFeltutleder.hentFeltutleder(K9SakOppgavesaksbehandlingstidUtleder::class.java.canonicalName)
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKTIV_VENTEARSAK,
                    område = område,
                    visningsnavn = "Aktiv venteårsak",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "Venteårsak"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.AKTIV_VENTEFRIST,
                    område = område,
                    visningsnavn = "Aktiv ventefrist",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Timestamp",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.HELAUTOMATISK_BEHANDLET,
                    område = område,
                    visningsnavn = "Helautomatisk behandlet",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "boolean",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.VEDTAKSDATO,
                    område = område,
                    visningsnavn = "Vedtaksdato",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Timestamp",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.NYE_KRAV,
                    område = område,
                    visningsnavn = "Søknad inneholder nye perioder",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "boolean",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.BARE_NYE_KRAV,
                    område = område,
                    visningsnavn = "Søknad inneholder bare nye perioder",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "boolean",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.ANTALL_OMSOKTE_DAGER,
                    område = område,
                    visningsnavn = "Antall dager man har søkt om støtte for",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Integer",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.FRA_ENDRINGSDIALOG,
                    område = område,
                    visningsnavn = "Oppdatert gjennom endringsdialog",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "boolean",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.HASTESAK,
                    område = område,
                    visningsnavn = "Hastesak",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "boolean",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.UTENLANDSTILSNITT,
                    område = område,
                    visningsnavn = "Utenlandssak",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "boolean",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.DIREKTEUTBETALING,
                    område = område,
                    visningsnavn = "Direkteutbetaling til søker",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "boolean",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.SOKNADSARSAK,
                    område = område,
                    visningsnavn = "Søknadsårsak - gjelder kun omsorgspenger",
                    beskrivelse = null,
                    listetype = true,
                    tolkesSom = "String",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "søknadsårsak"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.BEHANDLINGSARSAK,
                    område = område,
                    visningsnavn = "Behandlingsårsak",
                    beskrivelse = null,
                    listetype = true,
                    tolkesSom = "String",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "behandlingsårsak"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.JOURNALFORT,
                    område = område,
                    visningsnavn = "Journalført",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "boolean",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.JOURNALFORT_TIDSPUNKT,
                    område = område,
                    visningsnavn = "Journalført tidspunkt",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Timestamp",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.JOURNALPOST_ID,
                    område = område,
                    visningsnavn = "Journalpost-ID",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.OVERSENDT_KABAL_TIDSPUNKT,
                    område = område,
                    visningsnavn = "Tidspunkt for eventuell overføring til klageinstans",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Timestamp",
                    synlighet = Synlighet.INTERNT,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.OVERSENDT_KLAGEINSTANS_TIDSPUNKT,
                    område = område,
                    visningsnavn = "Tidspunkt for eventuell overføring til klageinstans",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Timestamp",
                    synlighet = Synlighet.INTERNT,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.FORSTE_FEILUTBETALING_DATO,
                    område = område,
                    visningsnavn = "Første dato som har feilutbetaling",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Timestamp",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.FEILUTBETALT_BELOP,
                    område = område,
                    visningsnavn = "Feilutbetalt beløp (kun tilbakekreving)",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Integer",
                    synlighet = Synlighet.OVER_STREKEN,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.FERDIGSTILT_TIDSPUNKT,
                    område = område,
                    visningsnavn = "Ferdigstilt tidspunkt",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Timestamp",
                    synlighet = Synlighet.INTERNT,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.FERDIGSTILT_ENHET,
                    område = område,
                    visningsnavn = "Ferdigstilt av enhet",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "String",
                    synlighet = Synlighet.UNDER_STREKEN,
                    kodeverkreferanse = Kodeverkreferanse(område = "K9", eksternId = "behandlendeEnhet"),
                    transientFeltutleder = null
                ),
                Feltdefinisjon(
                    id = null,
                    eksternId = K9FeltIder.FAGSAK_AR,
                    område = område,
                    visningsnavn = "Fagsak år",
                    beskrivelse = null,
                    listetype = false,
                    tolkesSom = "Integer",
                    synlighet = Synlighet.INTERNT,
                    kodeverkreferanse = null,
                    transientFeltutleder = null
                )
            )
        )
    }
}
