package no.nav.k9.los.oppgavemottak.feltutlederforlagring

class AkkumulertVentetidAnnetIkkeSaksbehandlingstid : AkkumulerDuration(beslutningsfelt = "avventerAnnetIkkeSaksbehandlingstid", målfelt = "akkumulertVentetidAnnetIkkeSaksbehandlingstidForTidligereVersjoner")