apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-los-api
  namespace: default
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8020
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://k9-los-api.dev.adeo.no
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  fasitResources:
    used:
      - alias: appdynamics
        resourceType: applicationproperties
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/dev/srvk9los
      - mountPath: /var/run/secrets/nais.io/azuread
        kvPath: /azuread/data/dev/creds/k9-los-api
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/k9-los-api/default
  sidecar: true
  webproxy: true
  env:
    - name: NAIS_STS_DISCOVERY_ENDPOINT
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: AZURE_CLIENT_ID
      value: 5afad323-c9df-4e14-b481-b278e9d2bf69
    - name: AZURE_AUTHORIZED_CLIENTS
      value: 5617f485-23fd-4d15-86bc-978ee2163c5a
    - name: AZURE_V1_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration
    - name: AZURE_V2_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
    - name: AZURE_TOKEN_ENDPOINT
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
    - name: OPPGAVE_BASE_URI
      value: https://oppgave.nais.preprod.local
    - name: DB_URL
      value: jdbc:postgresql://b27dbvl014.preprod.local:5432/k9-los
    - name: DB_VAULT_MOUNTPATH
      value: postgresql/preprod-fss/

    - name: PDL_URL
      value: https://pdl-api.nais.preprod.local/graphql

      # Nav applikasjoner
    - name: APP_K9SAK_URL
      value: https://k9-sak.nais.preprod.local/k9/sak/api

    - name: APP_OMSORGSPENGER_URL
      value: https://omsorgspenger-sak.dev.intern.nav.no

      # Kafka
    - name: BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TOPIC
      value: privat-k9-aksjonspunkthendelse
    - name: KAFKA_PUNSJAKSJONSPUNKTHENDELSE_TOPIC
      value: privat-k9punsj-aksjonspunkthendelse-v1
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TILBAKE_TOPIC
      value: privat-tilbakekreving-k9loshendelse-v1
    - name: KAFKA_SAKOGBEHANDLING_TOPIC
      value: aapen-sob-oppgaveHendelse-v1
    - name: KAFKA_STATISTIKK_SAK_TOPIC
      value: privat-k9statistikk-sak-v1
    - name: KAFKA_STATISTIKK_BEHANDLING_TOPIC
      value: privat-k9statistikk-behandling-v1

      # ABAC
    - name: ABAC_PDP_ENDPOINT_URL
      value: http://abac-k9.teamabac.svc.nais.local/application/authorize

    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
      value: NON-PROD

      # Audit logging
    - name: AUDITLOGGER_ENABLED
      value: "true"
    - name: AUDITLOGGER_VENDOR
      value: "k9"
    - name: AUDITLOGGER_PRODUCT
      value: "k9-los-api"

      # token scope
    - name: OMSORGSPENGER_SAK_SCOPE
      value: "3ebacf0c-2409-4ae7-8507-07c8da9ddd25/.default"
