apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-los-api
  namespace: default
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8020
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://k9-los-api.nais.preprod.local
    - https://k9-los-api.nais.io
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/dev/srvk9los
      - mountPath: /var/run/secrets/nais.io/azuread
        kvPath: /azuread/data/dev/creds/k9-los-api
      - mountPath: /var/run/secrets/nais.io/application
        kvPath: /kv/preprod/fss/k9-los-api/default
  sidecar: true
  webproxy: true
  env:
    - name: NAIS_STS_DISCOVERY_ENDPOINT
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: AZURE_CLIENT_ID
      value: 5afad323-c9df-4e14-b481-b278e9d2bf69
    - name: AZURE_AUTHORIZED_CLIENTS
      value: a084abb8-6a38-4506-84c2-e4ac8b438a05
    - name: AZURE_V1_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration
    - name: AZURE_V2_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
    - name: AZURE_TOKEN_ENDPOINT
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
    - name: OPPGAVE_BASE_URI
      value: https://oppgave.nais.preprod.local
    - name: DB_URL
      value: jdbc:postgresql://b27dbvl014.preprod.local:5432/k9-los
    - name: DB_VAULT_MOUNTPATH
      value: postgresql/preprod-fss/
    - name: COOKIE_NAME
      value: selvbetjening-idtoken

    - name: PDL_URL
      value: https://pdl-api.nais.preprod.local/graphql

      # Kafka 
    - name: BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TOPIC
      value: privat-k9-aksjonspunkthendelse
    - name: KAFKA_SAKOGBEHANDLING_TOPIC
      value: aapen-sob-oppgaveHendelse-v1
    - name: KAFKA_STATISTIKK_SAK_TOPIC
      value: privat-k9statistikk-sak-v1
    - name: KAFKA_STATISTIKK_BEHANDLING_TOPIC
      value: privat-k9statistikk-behandling-v1
      
      # ABAC
    - name: ABAC_PDP_ENDPOINT_URL
      value: https://abac-k9.nais.preprod.local/application/authorize
      # https://wasapp-q1.adeo.no/asm-pdp/authorize
      
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
      value: NON-PROD  