apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-los-api
  namespace: default
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8020
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://k9-los-api.nais.preprod.local
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/dev/srvk9los
      - mountPath: /var/run/secrets/nais.io/application
        kvPath: /kv/preprod/fss/k9-los-api/default
  sidecar: true
  webproxy: true
  env:
    - name: NAIS_STS_DISCOVERY_ENDPOINT
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: AZURE_CLIENT_ID
      value: b32ae17c-0276-4006-9507-4ef49e0e5e20
    - name: AZURE_AUTHORIZED_CLIENTS
      value: a6aef297-b9c9-4cac-82be-060d4fa68bb8
    - name: AZURE_V1_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration
    - name: AZURE_V2_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
    - name: HENTE_DOKUMENT_SCOPES
      value: 97f0b1bc-6aa9-4d44-a3c7-60b4318fbec4/.default
    - name: OPPGAVE_BASE_URI
      value: https://oppgave.nais.preprod.local
    - name: DB_URL
      value: jdbc:postgresql://b27dbvl014.preprod.local:5432/k9-los
    - name: DB_VAULT_MOUNTPATH
      value: postgresql/preprod-fss/
    - name: COOKIE_NAME
      value: selvbetjening-idtoken

    - name: TPS_PROXY_V1_URL
      value: https://tps-proxy-q1.nais.preprod.local/api/v1

      # Kafka 
    - name: BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TOPIC
      value: privat-k9-aksjonspunkthendelse

      #Mq sak og behandling
    - name: MQGATEWAY02_NAME
      value: MQ1LSC02
    - name: MQGATEWAY02_HOSTNAME
      value: b27apvl176.preprod.local
    - name: MQGATEWAY02_PORT
      value: '1413'