apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-los-api
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8020
  liveness:
    path: health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: "4000m"
      memory: "4096Mi"
    requests:
      cpu: "1000m"
      memory: "2048Mi"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/dev/srvk9los
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/k9-los-api/k9saksbehandling
  webproxy: true
  kafka:
    pool: nav-dev
    streams: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: k9-los-oidc-auth-proxy
          namespace: k9saksbehandling
        - application: k9-los-web
          namespace: k9saksbehandling
          cluster: dev-gcp
        - application: k9-sak
          namespace: k9saksbehandling
  ingresses:
    - https://k9-los-api.dev-fss-pub.nais.io
  env:
    - name: OPPGAVE_BASE_URI
      value: https://oppgave.nais.preprod.local
    - name: DB_URL
      value: jdbc:postgresql://b27dbvl014.preprod.local:5432/k9-los
    - name: DB_VAULT_MOUNTPATH
      value: postgresql/preprod-fss/

    - name: PDL_URL
      value: https://pdl-api.nais.preprod.local/graphql

      # Nav applikasjoner
    - name: APP_K9SAK_URL
      value: https://k9-sak.nais.preprod.local/k9/sak/api
    - name: APP_K9SAK_FRONTEND_URL
      value: https://k9.dev.intern.nav.no/k9/web

      # Kafka
    - name: BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TOPIC
      value: k9saksbehandling.k9sak-aksjonspunkthendelse
    - name: KAFKA_KLAGE_TIL_LOS_TOPIC
      value: k9saksbehandling.oppgavemeldinger-klage-til-los
    - name: KAFKA_PUNSJAKSJONSPUNKTHENDELSE_TOPIC
      value: k9saksbehandling.punsj-aksjonspunkthendelse-v1
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TILBAKE_TOPIC
      value: k9saksbehandling.tilbakekreving-hendelse-los
    - name: KAFKA_SAKOGBEHANDLING_TOPIC
      value: personoversikt.modia-soknadsstatus-hendelse
    - name: KAFKA_STATISTIKK_SAK_TOPIC
      value: k9saksbehandling.privat-k9statistikk-sak
    - name: KAFKA_AAPEN_STATISTIKK_SAK_TOPIC
      value: k9saksbehandling.aapen-k9statistikk-sak-v2
    - name: KAFKA_STATISTIKK_BEHANDLING_TOPIC
      value: k9saksbehandling.privat-k9statistikk-behandling
    - name: KAFKA_AAPEN_STATISTIKK_BEHANDLING_TOPIC
      value: k9saksbehandling.aapen-k9statistikk-behandling-v2
    - name: KAFKA_K9SAK_TOPIC
      value: k9saksbehandling.privat-k9-produksjonsstyring-sak-v1
    - name: KAFKA_K9PUNSJ_TOPIC
      value: k9saksbehandling.privat-k9-produksjonsstyring-punsj-v1

      # ABAC
    - name: ABAC_PDP_ENDPOINT_URL
      value: http://abac-k9.k9saksbehandling.svc.nais.local/application/authorize

      # open telemetry
    - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
      value: "https://elastic-apm.adeo.no"
    - name: "OTEL_METRICS_EXPORTER"
      value: "otlp"
    - name: "OTEL_LOGS_EXPORTER"
      value: "none"
    - name: "OTEL_RESOURCE_ATTRIBUTES"
      value: "service.name=k9-los-api,service.version=k9-los-api,deployment.environment=q"
    - name: "OTEL_TRACES_EXPORTER"
      value: "otlp"


      # Audit logging
    - name: AUDITLOGGER_ENABLED
      value: "true"
    - name: AUDITLOGGER_VENDOR
      value: "k9"
    - name: AUDITLOGGER_PRODUCT
      value: "k9-los-api"

      # feature toggles
    - name: NY_OPPGAVESTYRING
      value: "true"
    - name: NY_OPPGAVESTYRING_DVH_SENDING
      value: "false"
    - name: NY_OPPGAVESTYRING_REST_API
      value: "true"
    - name: K9SAK_CONSUMER_AIVEN
      value: "true"
    - name: PUNSJ_CONSUMER_AIVEN
      value: "true"
    - name: TILBAKE_CONSUMER_AIVEN
      value: "true"
