apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-los-api
  namespace: default
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8020
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  ingresses:
    - https://k9-los-api.nais.adeo.no
    - https://k9-los-api.prod-fss.nais.io
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/prod/srvk9los
      - mountPath: /var/run/secrets/nais.io/azuread
        kvPath: /azuread/data/prod/creds/k9-los-api
      - mountPath: /var/run/secrets/nais.io/application
        kvPath: /kv/prod/fss/k9-los-api/default
  sidecar: true
  webproxy: true
  env:
    - name: NAIS_STS_DISCOVERY_ENDPOINT
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
    - name: AZURE_CLIENT_ID
      value: 37066d6c-842c-470a-85f1-3149a37da2c2
    - name: AZURE_AUTHORIZED_CLIENTS
      value: 0dc85ed5-a4d7-4893-8424-700ee6725067
    - name: AZURE_V1_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/.well-known/openid-configuration
    - name: AZURE_V2_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration
    - name: AZURE_TOKEN_ENDPOINT
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/oauth2/v2.0/token
    - name: OPPGAVE_BASE_URI
      value: https://oppgave.nais.adeo.no
    - name: DB_URL
      value: jdbc:postgresql://A01DBVL012.adeo.no:5432/k9-los
    - name: DB_VAULT_MOUNTPATH
      value: postgresql/prod-fss/
    - name: COOKIE_NAME
      value: selvbetjening-idtoken

    - name: PDL_URL
      value: https://pdl-api.nais.adeo.no/graphql

      # Kafka 
    - name: BOOTSTRAP_SERVERS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TOPIC
      value: privat-k9-aksjonspunkthendelse
    - name: KAFKA_SAKOGBEHANDLING_TOPIC
      value: aapen-sob-oppgaveHendelse-v1

      # ABAC
    - name: ABAC_PDP_ENDPOINT_URL
      value: https://wasapp.adeo.no/asm-pdp/authorize