apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-los-api
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8020
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      memory: "8096Mi"
    requests:
      cpu: "500m"
      memory: "1560Mi"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "elastic-apm"
        - id: "grafana-lgtm"

  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/prod/srvk9los
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/fss/k9-los-api/k9saksbehandling
  webproxy: true
  kafka:
    pool: nav-prod
    streams: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        # Kun de gruppene brukeren er medlem av vil bli lagt til i claims på tokenet.
        groups:
          # 0000-GA-k9-beslutter
          - id: e5f1ba3d-c29f-4b0c-9cb1-b15fc4253fa3
          # 0000-GA-Egne_ansatte
          - id: e750ceb5-b70b-4d94-b4fa-9d22467b786b
          # 0000-GA-Strengt_Fortrolig_Adresse
          - id: ad7b87a6-9180-467c-affc-20a566b0fec0
          # 0000-GA-Fortrolig_Adresse
          - id: 9ec6487d-f37a-4aad-a027-cd221c1ac32b
          # 0000-GA-k9-overstyrer
          - id: f6b0f0bd-3716-4c5a-aa7d-c8b72fdc40b5
          # 0000-GA-k9-saksbehandler
          - id: 466d0df7-22ba-4c68-b848-73478cfd0486
          # 0000-GA-k9-veileder
          - id: be11a922-59a2-4afa-b5ad-b9e9bd445268
          # 0000-GA-k9-drift
          - id: 1509dc91-a955-4e72-b64c-2f049e37c0c6
          # 0000-GA-k9-oppgavestyrer
          - id: f3743660-4c76-4845-885f-f38ad478645f
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: k9-los-web
          namespace: k9saksbehandling
          cluster: prod-gcp
        - application: k9-sak
          namespace: k9saksbehandling
  ingresses:
    - https://k9-los-api.prod-fss-pub.nais.io
  env:
    - name: OPPGAVE_BASE_URI
      value: https://oppgave.nais.adeo.no
    - name: DB_URL
      value: jdbc:postgresql://a01dbvl041.adeo.no:5432/k9-los
    - name: DB_VAULT_MOUNTPATH
      value: postgresql/prod-fss/

    - name: PDL_URL
      value: https://pdl-api.nais.adeo.no/graphql

      # Nav applikasjoner
    - name: APP_K9SAK_URL
      value: https://k9-sak.nais.adeo.no/k9/sak/api
    - name: APP_K9SAK_FRONTEND_URL
      value: https://k9.intern.nav.no/k9/web
    - name: APP_K9PUNSJ_FRONTEND_URL
      value: https://k9-punsj-frontend.intern.nav.no

      # Kafka
    - name: BOOTSTRAP_SERVERS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TOPIC
      value: k9saksbehandling.k9sak-aksjonspunkthendelse
    - name: KAFKA_KLAGE_TIL_LOS_TOPIC
      value: k9saksbehandling.oppgavemeldinger-klage-til-los
    - name: KAFKA_PUNSJAKSJONSPUNKTHENDELSE_TOPIC
      value: k9saksbehandling.punsj-aksjonspunkthendelse-v1
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TILBAKE_TOPIC
      value: k9saksbehandling.tilbakekreving-hendelse-los
    - name: KAFKA_SAKOGBEHANDLING_TOPIC
      value: personoversikt.modia-soknadsstatus-hendelse
    - name: KAFKA_AAPEN_STATISTIKK_SAK_TOPIC
      value: k9saksbehandling.aapen-k9statistikk-sak-v2
    - name: KAFKA_AAPEN_STATISTIKK_BEHANDLING_TOPIC
      value: k9saksbehandling.aapen-k9statistikk-behandling-v2
    - name: KAFKA_K9SAK_TOPIC
      value: k9saksbehandling.privat-k9-produksjonsstyring-sak-v1
    - name: KAFKA_K9PUNSJ_TOPIC
      value: k9saksbehandling.privat-k9-produksjonsstyring-punsj-v1

      # opentelemetry
    - name: "OTEL_RESOURCE_ATTRIBUTES"
      value: "service.name=k9-los-api,service.namespace=k9saksbehandling,deployment.environment=p,nais.backend=elastic-apm;grafana-lgtm"

      # ABAC
    - name: ABAC_PDP_ENDPOINT_URL
      value: http://abac-k9.k9saksbehandling.svc.nais.local/application/authorize

      # Audit logging
    - name: AUDITLOGGER_ENABLED
      value: "true"
    - name: AUDITLOGGER_VENDOR
      value: "k9"
    - name: AUDITLOGGER_PRODUCT
      value: "k9-los-api"

    # Gruppenavn for roller fra Active Directory
    # 0000-GA-k9-beslutter
    - name: BRUKER_GRUPPE_ID_BESLUTTER
      value: e5f1ba3d-c29f-4b0c-9cb1-b15fc4253fa3
    # 0000-GA-Egne_ansatte
    - name: BRUKER_GRUPPE_ID_EGENANSATT
      value: e750ceb5-b70b-4d94-b4fa-9d22467b786b
    # 0000-GA-Strengt_Fortrolig_Adresse
    - name: BRUKER_GRUPPE_ID_KODE6
      value: ad7b87a6-9180-467c-affc-20a566b0fec0
    # 0000-GA-Fortrolig_Adresse
    - name: BRUKER_GRUPPE_ID_KODE7
      value: 9ec6487d-f37a-4aad-a027-cd221c1ac32b
    # 0000-GA-k9-overstyrer
    - name: BRUKER_GRUPPE_ID_OVERSTYRER
      value: f6b0f0bd-3716-4c5a-aa7d-c8b72fdc40b5
    # 0000-GA-k9-saksbehandler
    - name: BRUKER_GRUPPE_ID_SAKSBEHANDLER
      value: 466d0df7-22ba-4c68-b848-73478cfd0486
    # 0000-GA-k9-veileder
    - name: BRUKER_GRUPPE_ID_VEILEDER
      value: be11a922-59a2-4afa-b5ad-b9e9bd445268
    # 0000-GA-k9-drift
    - name: BRUKER_GRUPPE_ID_DRIFT
      value: 1509dc91-a955-4e72-b64c-2f049e37c0c6
    # 0000-GA-k9-oppgavestyrer
    - name: BRUKER_GRUPPE_ID_OPPGAVESTYRER
      value: f3743660-4c76-4845-885f-f38ad478645f

      # feature toggles
    - name: NY_OPPGAVESTYRING
      value: "true"
    - name: NY_OPPGAVESTYRING_DVH_SENDING
      value: "true"
    - name: NY_OPPGAVESTYRING_REST_API
      value: "false"
    - name: K9SAK_CONSUMER_AIVEN
      value: "true"
    - name: PUNSJ_CONSUMER_AIVEN
      value: "true"
    - name: TILBAKE_CONSUMER_AIVEN
      value: "true"

    - name: NOKKELTALL_ENHETER
      value: "4403 Nav ARBEID OG YTELSER KRISTIANIA,4410 Nav ARBEID OG YTELSER SØRLANDET"
