apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-los-api
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8020
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      memory: "8096Mi"
    requests:
      cpu: "500m"
      memory: "1560Mi"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "elastic-apm"
        - id: "grafana-lgtm"

  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/prod/srvk9los
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/fss/k9-los-api/k9saksbehandling
  webproxy: true
  kafka:
    pool: nav-prod
    streams: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: k9-los-oidc-auth-proxy
          namespace: k9saksbehandling
        - application: k9-los-web
          namespace: k9saksbehandling
          cluster: prod-gcp
        - application: k9-sak
          namespace: k9saksbehandling
  ingresses:
    - https://k9-los-api.prod-fss-pub.nais.io
  env:
    - name: OPPGAVE_BASE_URI
      value: https://oppgave.nais.adeo.no
    - name: DB_URL
      value: jdbc:postgresql://A01DBVL012.adeo.no:5432/k9-los
    - name: DB_VAULT_MOUNTPATH
      value: postgresql/prod-fss/

    - name: PDL_URL
      value: https://pdl-api.nais.adeo.no/graphql

      # Nav applikasjoner
    - name: APP_K9SAK_URL
      value: https://k9-sak.nais.adeo.no/k9/sak/api
    - name: APP_K9SAK_FRONTEND_URL
      value: https://k9.intern.nav.no/k9/web
    - name: APP_K9PUNSJ_FRONTEND_URL
      value: https://k9-punsj-frontend.intern.nav.no

      # Kafka
    - name: BOOTSTRAP_SERVERS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TOPIC
      value: k9saksbehandling.k9sak-aksjonspunkthendelse
    - name: KAFKA_KLAGE_TIL_LOS_TOPIC
      value: k9saksbehandling.oppgavemeldinger-klage-til-los
    - name: KAFKA_PUNSJAKSJONSPUNKTHENDELSE_TOPIC
      value: k9saksbehandling.punsj-aksjonspunkthendelse-v1
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TILBAKE_TOPIC
      value: k9saksbehandling.tilbakekreving-hendelse-los
    - name: KAFKA_SAKOGBEHANDLING_TOPIC
      value: personoversikt.modia-soknadsstatus-hendelse
    - name: KAFKA_AAPEN_STATISTIKK_SAK_TOPIC
      value: k9saksbehandling.aapen-k9statistikk-sak-v2
    - name: KAFKA_AAPEN_STATISTIKK_BEHANDLING_TOPIC
      value: k9saksbehandling.aapen-k9statistikk-behandling-v2
    - name: KAFKA_K9SAK_TOPIC
      value: k9saksbehandling.privat-k9-produksjonsstyring-sak-v1
    - name: KAFKA_K9PUNSJ_TOPIC
      value: k9saksbehandling.privat-k9-produksjonsstyring-punsj-v1

      # opentelemetry
    - name: "OTEL_RESOURCE_ATTRIBUTES"
      value: "service.name=k9-los-api,service.namespace=k9saksbehandling,deployment.environment=p,nais.backend=elastic-apm;grafana-lgtm"

      # ABAC
    - name: ABAC_PDP_ENDPOINT_URL
      value: http://abac-k9.k9saksbehandling.svc.nais.local/application/authorize

      # Audit logging
    - name: AUDITLOGGER_ENABLED
      value: "true"
    - name: AUDITLOGGER_VENDOR
      value: "k9"
    - name: AUDITLOGGER_PRODUCT
      value: "k9-los-api"

      # feature toggles
    - name: NY_OPPGAVESTYRING
      value: "true"
    - name: NY_OPPGAVESTYRING_DVH_SENDING
      value: "true"
    - name: NY_OPPGAVESTYRING_REST_API
      value: "false"
    - name: K9SAK_CONSUMER_AIVEN
      value: "true"
    - name: PUNSJ_CONSUMER_AIVEN
      value: "true"
    - name: TILBAKE_CONSUMER_AIVEN
      value: "true"
