apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-los-api
  namespace: default
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8020
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  ingresses:
    - https://k9-los-api.nais.adeo.no
    - https://k9-los-api.prod-fss.nais.io
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/prod/srvk9los
      - mountPath: /var/run/secrets/nais.io/azuread
        kvPath: /azuread/data/prod/creds/k9-los-api
      - mountPath: /var/run/secrets/nais.io/application
        kvPath: /kv/prod/fss/k9-los-api/default
  sidecar: true
  webproxy: true
  env:
    - name: NAIS_STS_DISCOVERY_ENDPOINT
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
    - name: AZURE_CLIENT_ID
      value: cb751642-883c-48d3-9f82-06cc72c3e4b9
    - name: AZURE_AUTHORIZED_CLIENTS
      value: 84ef0905-64b3-440b-8f6a-0d88ef81a0f0
    - name: AZURE_V1_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/.well-known/openid-configuration
    - name: AZURE_V2_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration
    - name: AZURE_TOKEN_ENDPOINT
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
    - name: OPPGAVE_BASE_URI
      value: https://oppgave.nais.adeo.no
    - name: DB_URL
      value: jdbc:postgresql://b27dbvl014.prod.local:5432/k9-los
    - name: DB_VAULT_MOUNTPATH
      value: postgresql/prod-fss/
    - name: COOKIE_NAME
      value: selvbetjening-idtoken

    - name: PDL_URL
      value: https://pdl-api.nais.adeo.no/graphql

      # Kafka 
    - name: BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.adeo.no:8443
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TOPIC
      value: privat-k9-aksjonspunkthendelse

      # ABAC
    - name: ABAC_PDP_ENDPOINT_URL
      value: https://wasapp.adeo.no/asm-pdp/authorize