apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-los-api
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8020
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: "4000m"
      memory: "4096Mi"
    requests:
      cpu: "1000m"
      memory: "2048Mi"
  ingresses:
    - https://k9-los-api.nais.adeo.no
    - https://k9-los-api.prod-fss.nais.io
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /metrics
  fasitResources:
    used:
      - alias: appdynamics
        resourceType: applicationproperties
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/prod/srvk9los
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/fss/k9-los-api/k9saksbehandling
  sidecar: true
  webproxy: true
  kafka:
    pool: nav-prod
    streams: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: k9-los-oidc-auth-proxy
          namespace: k9saksbehandling
  env:
    - name: NAIS_STS_DISCOVERY_ENDPOINT
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
    - name: STS_AUDIENCE
      value: srvk9sak
    - name: OPPGAVE_BASE_URI
      value: https://oppgave.nais.adeo.no
    - name: DB_URL
      value: jdbc:postgresql://A01DBVL012.adeo.no:5432/k9-los
    - name: DB_VAULT_MOUNTPATH
      value: postgresql/prod-fss/

    - name: PDL_URL
      value: https://pdl-api.nais.adeo.no/graphql

      # Nav applikasjoner
    - name: APP_K9SAK_URL
      value: https://k9-sak.nais.adeo.no/k9/sak/api

    - name: APP_OMSORGSPENGER_URL
      value: https://omsorgspenger-sak.intern.nav.no

      # Kafka
    - name: BOOTSTRAP_SERVERS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TOPIC
      value: privat-k9-aksjonspunkthendelse
    - name: KAFKA_PUNSJAKSJONSPUNKTHENDELSE_TOPIC
      value: privat-k9punsj-aksjonspunkthendelse-v1
    - name: KAFKA_AKSJONSPUNKTHENDELSE_TILBAKE_TOPIC
      value: privat-tilbakekreving-k9loshendelse-v1
    - name: KAFKA_SAKOGBEHANDLING_TOPIC
      value: aapen-sob-oppgaveHendelse-v1
    - name: KAFKA_STATISTIKK_SAK_TOPIC
      value: privat-k9statistikk-sak-v1
    - name: KAFKA_STATISTIKK_BEHANDLING_TOPIC
      value: privat-k9statistikk-behandling-v1
    - name: KAFKA_K9SAK_TOPIC
      value: k9saksbehandling.privat-k9-produksjonsstyring-sak-v1
    - name: KAFKA_K9PUNSJ_TOPIC
      value: k9saksbehandling.privat-k9-produksjonsstyring-punsj-v1

      # ABAC
    - name: ABAC_PDP_ENDPOINT_URL
      value: http://abac-k9.teamabac.svc.nais.local/application/authorize

    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
      value: PROD

      # Audit logging
    - name: AUDITLOGGER_ENABLED
      value: "true"
    - name: AUDITLOGGER_VENDOR
      value: "k9"
    - name: AUDITLOGGER_PRODUCT
      value: "k9-los-api"

      # token scope
    - name: OMSORGSPENGER_SAK_SCOPE
      value: "api://prod-gcp.omsorgspenger.omsorgspenger-sak/.default"
