package no.nav.k9.los.nyoppgavestyring.domeneadaptere.k9.eventmottak


enum class EventHendelse {
    AKSJONSPUNKT_OPPRETTET,
    AKSJONSPUNKT_UTFØRT,
    AKSJONSPUNKT_TILBAKEFØR,
    AKSJONSPUNKT_AVBRUTT,
    AKSJONSPUNKT_HAR_ENDRET_BEHANDLENDE_ENHET,
    BEHANDLINGSKONTROLL_EVENT,
    VASKEEVENT,
    HASTESAK_MERKNAD_NY,
    HASTESAK_MERKNAD_FJERNET,
    ENDRET_BEHANDLINGMERKNAD
}
