name: Build and deploy slette_V1
on:
  push:
    branches:
      - slette_V1

jobs:
  test:
    uses: navikt/sif-gha-workflows/.github/workflows/gradle-test.yml@main
    permissions:
      contents: read
    secrets: inherit
    with:
      readertoken: true
      javaversion: 21

  build:
    uses: navikt/sif-gha-workflows/.github/workflows/gradle-build.yml@main
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    with:
      readertoken: true
      team: k9saksbehandling
      javaversion: 21

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [ test, build ]
    environment: "dev-fss:k9saksbehandling"
    permissions:
      contents: read
      id-token: write
      actions: read
    outputs:
      image: ${{ needs.build.outputs.image }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy til dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
          CLUSTER: dev-fss
          RESOURCE: nais/naiserator.yaml
          VARS: nais/dev-fss.json