name: Dependency Submission
on:
  push:
    branches: master
    paths:
      - "build.gradle.kts"
      - '.github/workflows/dependency-submission.yml'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Scan & submit dependencies
        uses: mikepenz/gradle-dependency-submission@aa82af7186ba17eb630a7d47c840ba8a3185ac91
        with:
          fail-on-error: true
          gradle-build-configuration: |-
            compileClasspath
        env:
          GITHUB_USERNAME: k9-los-api
          GITHUB_PASSWORD: ${{ secrets.READER_TOKEN }}
