name: Deploy manuelt
on:
  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string
        description: 'Image tag to deploy (example 2023.03.10.080433-f821119). OBS! vær oppmerksom på at naiserator.yml, dev-fss/prod-fss.json ikke oppdateres ved å deploye på denne måten.'
      environment:
        required: true
        type: choice
        description: 'The environment to deployed to (dev|prod)'
        options:
          - dev
          - prod

jobs:
  deploy:
    name: Migrer og deploy
    runs-on: ubuntu-latest
    timeout-minutes: 370
    environment: ${{ inputs.environment }}-fss:k9saksbehandling
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Logg inn i GAR
        id: login
        uses: nais/login@bb6c3e1e14e53d40d69d0d092bd2fce2e39ae3bf # v0
        with:
          team: k9saksbehandling
      - name: Kjør Flyway
        uses: nais/deploy/actions/deploy@fc3eae3edebabdf67f7592102ae16176d5ba3b5f # v2
        env:
          CLUSTER: ${{ inputs.environment }}-fss
          RESOURCE: nais/db-migration.yml
          VARS: nais/${{ inputs.environment }}-fss.json
          IMAGE: ${{ steps.login.outputs.registry }}/${{ github.repository }}:${{ inputs.image }}
          TIMEOUT: 355m
      - name: Deploy applikasjon
        uses: nais/deploy/actions/deploy@fc3eae3edebabdf67f7592102ae16176d5ba3b5f # v2
        env:
          CLUSTER: ${{ inputs.environment }}-fss
          RESOURCE: nais/naiserator.yml
          VARS: nais/${{ inputs.environment }}-fss.json
          IMAGE: ${{ steps.login.outputs.registry }}/${{ github.repository }}:${{ inputs.image }}
          TIMEOUT: 10m
