name: Vulnerabilities scanning of dependencies
on:
  schedule:
    - cron:  '0 0 * * 1'
  workflow_dispatch:
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - uses: snyk/actions/setup@master

      - name: Run Snyk to check for vulnerabilities
        run: >
          snyk monitor
          --org=k9saksbehandling
          --project-name=${{ github.repository }}
          --remote-repo-url=https://github.com/${{ github.repository }}.git
          --configuration-matching=^runtimeClasspath$
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
